const productsData = [
  { id: 'bathroom-vanity', category: 'Bathroom', title: 'Bathroom Vanity', img: 'bathroom1.png', desc: 'Modern bathroom vanity design with premium fixtures.' },
  { id: 'bathroom-storage', category: 'Bathroom', title: 'Bathroom Storage', img: 'bathroom2.png', desc: 'Efficient bathroom storage solutions for tight spaces.' },
  { id: 'bathroom-fittings', category: 'Bathroom', title: 'Bathroom Fittings', img: 'bathroom3.png', desc: 'Custom bathroom fittings and mirror cabinets.' },
  { id: 'kids-study-area', category: 'Kids Bedroom', title: 'Kids Study Area', img: 'kids bedroom1.png', desc: 'Ergonomic kids study area integrated with wardrobe.' },
  { id: 'kids-bunk-bed', category: 'Kids Bedroom', title: 'Kids Bunk Bed', img: 'kids bedroom2.png', desc: 'Space-saving bunk bed with safety rails and built-in storage.' },
  { id: 'kids-wardrobe', category: 'Kids Bedroom', title: 'Kids Wardrobe', img: 'kids bedroom3.png', desc: 'Colorful and accessible wardrobe designed for children.' },
  { id: 'kids-play-area', category: 'Kids Bedroom', title: 'Kids Play Area', img: 'kids bedroom4.png', desc: 'Play area furniture prioritizing safety and fun.' },
  { id: 'washing-setup', category: 'Washing Area', title: 'Washing Setup', img: 'washing area 1.png', desc: 'Utility washing area setup with waterproof cabinetry.' },
  { id: 'washing-cabinets', category: 'Washing Area', title: 'Washing Cabinets', img: 'washing area 2.png', desc: 'Tall storage cabinets for washing and utility rooms.' },
  { id: 'washing-shelving', category: 'Washing Area', title: 'Washing Shelving', img: 'washing area 3.png', desc: 'Open and closed shelving for laundry organization.' },
  { id: 'custom-temple-area', category: 'Temple Area', title: 'Custom Temple Area', img: 'temple area 1.png', desc: 'Elegant and peaceful temple unit with intricate details.' },
  { id: 'modular-kitchen-system', category: 'Modular Kitchen', title: 'Modular Kitchen System', img: 'modular kitchen 1.png', desc: 'L-shaped modular kitchen with seamless handleless doors.' },
  { id: 'kitchen-island', category: 'Modular Kitchen', title: 'Kitchen Island', img: 'modular kitchen 2.png', desc: 'Central kitchen island offering prep space and dining.' },
  { id: 'kitchen-cabinets', category: 'Modular Kitchen', title: 'Kitchen Cabinets', img: 'modular kitchen 3.png', desc: 'High-gloss acrylic kitchen cabinets with soft-close.' },
  { id: 'royal-teak-bedroom-set', category: 'Bedroom', title: 'Royal Teak Bedroom Set', img: 'bed room 1.png', desc: 'A premium bedroom collection with coordinated bedside tables and wardrobe options.' },
  { id: 'premium-bedroom', category: 'Bedroom', title: 'Premium Bedroom', img: 'bed room 2.png', desc: 'Luxury bedroom with fine wooden finishing.' },
  { id: 'master-bedroom-set', category: 'Bedroom', title: 'Master Bedroom Set', img: 'bed room 3.png', desc: 'Luxurious master bedroom set featuring an upholstered headboard.' },
  { id: 'modern-bedroom-1', category: 'Bedroom', title: 'Modern Bedroom', img: 'bed room 4.png', desc: 'Modern bedroom layout with space-efficient design.' },
  { id: 'bedroom-storage', category: 'Bedroom', title: 'Bedroom Storage', img: 'bed room 5.png', desc: 'Smart bedroom storage solutions to keep your space clutter-free.' },
  { id: 'bedroom-interiors', category: 'Bedroom', title: 'Bedroom Interiors', img: 'bed room 6.png', desc: 'Complete bedroom interior setup tailored to your dimensions.' },
  { id: 'lounge-comfort-living', category: 'Living Room', title: 'Lounge Comfort Living', img: 'living room 1.png', desc: 'Plush setup designed for maximum relaxation.' },
  { id: 'living-room-space', category: 'Living Room', title: 'Living Room Space', img: 'living room 2.png', desc: 'Elegant and spacious living room setup.' },
  { id: 'custom-tv-unit', category: 'Living Room', title: 'Custom TV Unit', img: 'living room 3.png', desc: 'Wall-mounted TV entertainment unit with ambient backlighting.' },
  { id: 'living-room-lounge', category: 'Living Room', title: 'Living Room Lounge', img: 'living room 4.png', desc: 'Contemporary living room piece.' },
  { id: 'living-room-layout', category: 'Living Room', title: 'Living Room Layout', img: 'living room 5.png', desc: 'Complete living room layout integrating storage and seating.' },
  { id: 'living-room-decor', category: 'Living Room', title: 'Living Room Decor', img: 'living room 6.png', desc: 'Living room decor elements and accent furniture pieces.' },
  { id: 'living-room-seating', category: 'Living Room', title: 'Living Room Seating', img: 'living room 7.png', desc: 'Additional lounge seating for spacious living areas.' },
  { id: 'living-room-wall-unit', category: 'Living Room', title: 'Living Room Wall Unit', img: 'living room 8.png', desc: 'Comprehensive wall storage unit for the living space.' },
  { id: 'sliding-wardrobe', category: 'Wardrobe', title: 'Sliding Wardrobe', img: 'wardrobe1.jpeg', desc: 'Space-efficient sliding wardrobe with custom interior divisions.' },
  { id: 'premium-hinged-wardrobe', category: 'Wardrobe', title: 'Premium Hinged Wardrobe', img: 'wardrobe2.jpeg', desc: 'Classic hinged wardrobe with premium handles.' },
  { id: 'walk-in-wardrobe', category: 'Wardrobe', title: 'Walk-in Wardrobe', img: 'wardrobe3.png', desc: 'Spacious walk-in wardrobe for maximum storage.' },
  { id: 'solid-wood-dining-table', category: 'Dining', title: 'Solid Wood Dining Table', img: 'dining1.png', desc: '6-seater solid wood dining table perfect for family meals.' },
  { id: 'dining-area', category: 'Dining', title: 'Dining Area', img: 'dining2.png', desc: 'Complete dining room layout integrating storage and seating.' },
  { id: 'modern-dining-set', category: 'Dining', title: 'Modern Dining Set', img: 'dining3.png', desc: 'Modern dining set for contemporary homes.' },
  { id: 'living-room-sofa', category: 'Sofa', title: 'Living Room Sofa', img: 'sofa1.jpg', desc: 'Contemporary sofa piece with premium fabric upholstery.' },
  { id: 'l-shape-sofa', category: 'Sofa', title: 'L-Shape Sofa', img: 'sofa2.jpg', desc: 'Comfortable L-shape sofa for large families.' },
  { id: 'classic-sofa', category: 'Sofa', title: 'Classic Sofa', img: 'sofa3.jpg', desc: 'Classic sofa set with durable materials.' },
  { id: 'single-bed-1', category: 'Single Bed', title: 'Single Bed Design 1', img: 'singlebed1.png', desc: 'Comfortable and space-saving single bed.' },
  { id: 'single-bed-2', category: 'Single Bed', title: 'Single Bed Design 2', img: 'singlebed2.png', desc: 'Modern single bed with storage.' },
  { id: 'single-bed-3', category: 'Single Bed', title: 'Single Bed Design 3', img: 'singlebed3.png', desc: 'Premium wooden single bed.' },
  { id: 'dining-4', category: 'Dining', title: 'Dining Design 4', img: 'dining4.png', desc: 'Elegant dining set for your home.' },
  { id: 'dining-5', category: 'Dining', title: 'Dining Design 5', img: 'dining5.png', desc: 'Elegant dining set for your home.' },
  { id: 'dining-6', category: 'Dining', title: 'Dining Design 6', img: 'dining6.png', desc: 'Elegant dining set for your home.' },
  { id: 'dining-7', category: 'Dining', title: 'Dining Design 7', img: 'dining7.png', desc: 'Elegant dining set for your home.' },
  { id: 'dining-8', category: 'Dining', title: 'Dining Design 8', img: 'dining8.png', desc: 'Elegant dining set for your home.' },
  { id: 'dining-9', category: 'Dining', title: 'Dining Design 9', img: 'dining9.png', desc: 'Elegant dining set for your home.' },
  { id: 'dining-10', category: 'Dining', title: 'Dining Design 10', img: 'dining10.png', desc: 'Elegant dining set for your home.' },
  { id: 'wardrobe-4', category: 'Wardrobe', title: 'Wardrobe Design 4', img: 'wardrobe4.png', desc: 'Elegant and spacious wardrobe.' },
  { id: 'wardrobe-5', category: 'Wardrobe', title: 'Wardrobe Design 5', img: 'wardrobe5.png', desc: 'Elegant and spacious wardrobe.' },
  { id: 'wardrobe-6', category: 'Wardrobe', title: 'Wardrobe Design 6', img: 'wardrobe6.png', desc: 'Elegant and spacious wardrobe.' },
  { id: 'wardrobe-7', category: 'Wardrobe', title: 'Wardrobe Design 7', img: 'wardrobe7.png', desc: 'Elegant and spacious wardrobe.' },
  { id: 'wardrobe-8', category: 'Wardrobe', title: 'Wardrobe Design 8', img: 'wardrobe8.png', desc: 'Elegant and spacious wardrobe.' },
  { id: 'bedroom-7', category: 'Bedroom', title: 'Bedroom Design 7', img: 'bed room 7.jpeg', desc: 'Elegant and comfortable bedroom furniture.' },
  { id: 'living-coffee-table-1', category: 'Living Room', title: 'Living Room Coffee Table 1', img: 'living_coffe_table1.jpeg', desc: 'Stylish coffee table for the living room.' },
  { id: 'living-coffee-table-2', category: 'Living Room', title: 'Living Room Coffee Table 2', img: 'living_coffe_table2.jpeg', desc: 'Stylish coffee table for the living room.' },
  { id: 'living-coffee-table-3', category: 'Living Room', title: 'Living Room Coffee Table 3', img: 'living_coffe_table3.jpeg', desc: 'Stylish coffee table for the living room.' },
  { id: 'living-coffee-table-4', category: 'Living Room', title: 'Living Room Coffee Table 4', img: 'living_coffe_table4.jpeg', desc: 'Stylish coffee table for the living room.' },
  { id: 'wardrobe-9', category: 'Wardrobe', title: 'Wardrobe Design 9', img: 'wardrobe9.jpeg', desc: 'Elegant and spacious wardrobe.' },
  { id: 'wardrobe-10', category: 'Wardrobe', title: 'Wardrobe Design 10', img: 'wardrobe10.jpeg', desc: 'Elegant and spacious wardrobe.' },
  { id: 'wardrobe-11', category: 'Wardrobe', title: 'Wardrobe Design 11', img: 'wardrobe11.jpeg', desc: 'Elegant and spacious wardrobe.' },
  { id: 'wardrobe-12', category: 'Wardrobe', title: 'Wardrobe Design 12', img: 'wardrobe12.jpeg', desc: 'Elegant and spacious wardrobe.' },
  { id: 'wardrobe-13', category: 'Wardrobe', title: 'Wardrobe Design 13', img: 'wardrobe13.jpeg', desc: 'Elegant and spacious wardrobe.' },
  { id: 'wardrobe-14', category: 'Wardrobe', title: 'Wardrobe Design 14', img: 'wardrobe14.jpeg', desc: 'Elegant and spacious wardrobe.' },
  { id: 'wardrobe-15', category: 'Wardrobe', title: 'Wardrobe Design 15', img: 'wardrobe15.jpeg', desc: 'Elegant and spacious wardrobe.' },
  { id: 'tv-unit-1', category: 'TV Unit', title: 'TV Unit Design 1', img: 'tv_unit1.jpeg', desc: 'Modern and stylish TV unit.' },
  { id: 'tv-unit-2', category: 'TV Unit', title: 'TV Unit Design 2', img: 'tv_unit2.jpeg', desc: 'Modern and stylish TV unit.' },
  { id: 'tv-unit-3', category: 'TV Unit', title: 'TV Unit Design 3', img: 'tv_unit3.jpeg', desc: 'Modern and stylish TV unit.' },
  { id: 'tv-unit-4', category: 'TV Unit', title: 'TV Unit Design 4', img: 'tv_unit4.jpeg', desc: 'Modern and stylish TV unit.' },
  { id: 'tv-unit-5', category: 'TV Unit', title: 'TV Unit Design 5', img: 'tv_unit5.jpeg', desc: 'Modern and stylish TV unit.' },
  { id: 'tv-unit-6', category: 'TV Unit', title: 'TV Unit Design 6', img: 'tv_unit6.jpeg', desc: 'Modern and stylish TV unit.' }

];

const categoriesData = [
  { id: 'cat-living-room', category: 'Living Room', title: 'Living Room', img: 'living room 5.png', desc: 'Premium living room furniture and decor.' },
  { id: 'cat-bedroom', category: 'Bedroom', title: 'Bedroom', img: 'bed room 4.png', desc: 'Custom bedroom sets, beds, and bedside tables.' },
  { id: 'cat-kids-bedroom', category: 'Kids-Bedroom', title: 'Kids Bedroom', img: 'kids bedroom1.png', desc: 'Safe and fun furniture for kids rooms.' },
  { id: 'cat-modular-kitchen', category: 'Modular Kitchen', title: 'Modular Kitchen', img: 'modular kitchen 3.png', desc: 'L-shaped and straight modular kitchens.' },
  { id: 'cat-bathroom', category: 'Bathroom', title: 'Bathroom', img: 'bathroom1.png', desc: 'Bathroom vanities and storage solutions.' },
  { id: 'cat-washing-area', category: 'Washing Area', title: 'Washing Area', img: 'washing area 1.png', desc: 'Utility and washing room setups.' },
  { id: 'cat-temple-area', category: 'Temple Area', title: 'Temple Area', img: 'temple area 1.png', desc: 'Custom carved temple and pooja units.' },
  { id: 'cat-dining', category: 'Dining', title: 'Dining', img: 'dining3.png', desc: 'Dining tables and seating.' },
  { id: 'cat-sofa', category: 'Sofa', title: 'Sofa', img: 'sofa1.jpg', desc: 'Lounge seating and sofa sets.' },
  { id: 'cat-wardrobe', category: 'Wardrobe', title: 'Wardrobe', img: 'wardrobe3.png', desc: 'Sliding and hinged wardrobes.' },
  { id: 'cat-single-bed', category: 'Single Bed', title: 'Single Bed', img: 'singlebed1.png', desc: 'Comfortable and space-saving single beds.' },
  { id: 'cat-tv-unit', category: 'TV Unit', title: 'TV Unit', img: 'tv_unit1.jpeg', desc: 'Modern and stylish TV units for your living room.' }
];
